"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['saludo', 'saludo_a', 'foo']

# %% ../nbs/00_core.ipynb 4
def saludo():
    """Imprime Hola"""
    print('Hola!')
    return

saludo()

#| export
def saludo_a(to):
    """Imprime hola a un nombre"""
    print('Hola!', to)
    
    print('Espero que te encuentres bien')
    return

saludo_a('Raul')

show_doc(saludo_a)

# %% ../nbs/00_core.ipynb 5
def foo(): pass

# %% ../nbs/00_core.ipynb 6
def saludo():
    """Imprime Hola"""
    print('Hola!')
    return

# %% ../nbs/00_core.ipynb 8
def saludo_a(to):
    """Imprime hola a un nombre"""
    print('Hola!', to)
    
    print('Espero que te encuentres bien')
    return
